---
services:
  go-find-goodwill:
    container_name: go-find-goodwill
    image: toozej/go-find-goodwill:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.go-find-goodwill.rule=Host(`go-find-goodwill.test`)"
      # - "traefik.http.routers.go-find-goodwill.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.go-find-goodwill-secure.entrypoints=https"
      # - "traefik.http.routers.go-find-goodwill-secure.rule=Host(`go-find-goodwill.test`)"
      # - "traefik.http.routers.go-find-goodwill-secure.middlewares=headers@file"
      # - "traefik.http.routers.go-find-goodwill-secure.tls=true"
    # networks:
      # - traefik
